// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PracticalTask.WebApp.Data.Contexts;

#nullable disable

namespace PracticalTask.WebApp.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240412195300_Seed")]
    partial class Seed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("PracticalTask.WebApp.Data.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ApartmentNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HouseNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Town")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApartmentNumber = 52,
                            DateOfBirth = new DateTime(1967, 4, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            FirstName = "Genesis",
                            HouseNumber = 50,
                            LastName = "Morrow",
                            PhoneNumber = "+48567687234",
                            PostalCode = "02-969",
                            StreetName = "Waniliowa",
                            Town = "Warszawa"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(1995, 4, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            FirstName = "Sara",
                            HouseNumber = 63,
                            LastName = "Wells",
                            PhoneNumber = "+48567567764",
                            PostalCode = "45-580",
                            StreetName = "Bolka",
                            Town = "Opole"
                        },
                        new
                        {
                            Id = 3,
                            ApartmentNumber = 52,
                            DateOfBirth = new DateTime(1958, 4, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            FirstName = "Aniya",
                            HouseNumber = 118,
                            LastName = "Landry",
                            PhoneNumber = "+48964234678",
                            PostalCode = "02-642",
                            StreetName = "Maklakiewicza Jana",
                            Town = "Warszawa"
                        },
                        new
                        {
                            Id = 4,
                            ApartmentNumber = 89,
                            DateOfBirth = new DateTime(1984, 4, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            FirstName = "Mary",
                            HouseNumber = 30,
                            LastName = "Golden",
                            PhoneNumber = "+48726687234",
                            PostalCode = "25-102",
                            StreetName = "Agrestowa",
                            Town = "Kielce"
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateTime(2005, 4, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            FirstName = "Jonah",
                            HouseNumber = 141,
                            LastName = "Carter",
                            PhoneNumber = "+48654234890",
                            PostalCode = "31-999",
                            StreetName = "Soczyny",
                            Town = "Krakow"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
